import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { authOptions } from '../api/auth/[...nextauth]/route'

export const metadata: Metadata = {
  title: 'Administration',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  // If session not exists, display access denied message
  if (!(session?.user?.role === 'Admin')) {
    return (
      <div className='flex min-h-screen items-center justify-center'>
        <div className='flex flex-col items-center gap-2'>
          <h2 className='text-2xl font-semibold'>Access Denied</h2>
          <p>You do not have the necessary permissions to access this page.</p>
          <p>This route is restricted to administrators only.</p>
        </div>
      </div>
    )
  }
  return children
}
